FROM python:3.12-alpine AS base

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1
ENV PYTHONUNBUFFERED 1

WORKDIR /build

COPY . .
RUN pip install --no-cache-dir .

WORKDIR /
RUN rm -rf /build

ENTRYPOINT ["docker-nsupdate-ddns"]
